### ISSUE TITLE
group_vars/demo-secrets.yml

### ISSUE THREAD

**Issue by 10xSebastian** [cider-ci/cider-ci_documentation-source#3]
Hey Hey, just trying to install cider-ci.

I just realized somewhere in between that all users have the password secret now ;(

Maybe you should ask the user to change `group_vars/demo-secrets.yml` before he starts the installation process.

**Comment by DrTom** [comment]
Good point. 

On the other hand I don't want to make things too complicated for first time installers. 

I implemented recently a somewhat more secure approach in Madek which keeps things
(simple, strike that) easy. Maybe I should adopt it for Cider-CI. 

https://github.com/Madek/madek-deploy#the-madek_master_secret
https://github.com/Madek/madek-deploy/blob/madek-v3/group_vars/all.yml#L10-L19

**Comment by 10xSebastian** [comment]
:+1: true.

But now that I've a demo-installation how about a installation guide for production ;p ?

**Comment by DrTom** [comment]
Changed as indicated in https://github.com/cider-ci/cider-ci/tree/Cider-CI_3.5.0
